---
name: nftables-pk
summary: nftables is the new packet classification framework that replaces iptables
description: |
        Provides the latest version of nft command-line utility with the intention
        of replacing outdated and buggy packages provided by mainline Linux distributions.
        You may want to create a system-wide alias:

        snap alias nftables-pk.nft nft

        Remember to update your nftables scripts to point to /snap/bin/nft

        Configuration files are expected to be located in /var/snap/nftables-pk/common

        More documentation can be found at https://bitbucket.org/kravietz/snap-nftables/

# obtain version information from the `nftables` part below
adopt-info: nftables

assumes:
- snapd2.36       # for layouts
- common-data-dir # for config files

license: GPL-3.0
# https://docs.snapcraft.io/channels
grade: devel
confinement: strict
base: core18

# where configuration files need to go https://forum.snapcraft.io/t/snap-layouts/7207
layout:
  /etc/nftables.conf:
    bind-file: $SNAP_COMMON/nftables.conf
  /etc/nftables:
    bind: $SNAP_COMMON

parts:
  libnftnl:
    plugin: autotools
    source-type: git
    source: git://git.netfilter.org/libnftnl
    build-packages:
      - build-essential
      - bison
      - flex
      - asciidoc
      - libmnl-dev
      - libgmp-dev
      - libreadline-dev
      - pkg-config
  
  nftables:
    plugin: autotools
    source-type: git
    source: git://git.netfilter.org/nftables
    # https://forum.snapcraft.io/t/using-external-metadata/4642
    # compile using previously built libnftnl part
    configflags:
        - CFLAGS=-I$SNAPCRAFT_STAGE/include
        - LDFLAGS=-L$SNAPCRAFT_STAGE/lib
    # ensure libnftnl is built first
    after: [libnftnl]
    # set version from git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --abbrev=0)

apps:
  nft:
    command: nft
    plugs:
    # https://docs.snapcraft.io/supported-interfaces
    - network           # for netlink interface
    - network-control   # for /etc/iproute2/ files
    - firewall-control  # for actual nftables configuration